language: "php"
script: "make test-verbose"
# We install our prerequisite by hand here because Travis doesn't support
# pear, only pyrus, and pyrus isn't available for 5.2.
before_script:
  - "curl -o Console_CommandLine.tgz http://pear.php.net/get/Console_CommandLine-1.1.3.tgz"
  - "mkdir lib"
  - "tar xzvf Console_CommandLine.tgz -C lib --wildcards '*/Console' --strip-components 1"

php:
  - 5.2
  - 5.3
  - 5.4
