#!/usr/bin/env php
<?php
print "Revision history for PHP module Modyllic\n\n";
foreach (explode("\n",trim(`git for-each-ref --sort='-refname' --format='%(refname:short) %(authordate:short)' refs/tags/v*.*.*`)) as $tag) {
    list($tag_name,$tag_date) = explode(" ",$tag);
    print "$tag_name $tag_date\n\n";
    $changes = trim(`git show {$tag_name}:CHANGELOG 2> /dev/null`);
    if ( $changes == "" ) {
        $changes = "* No changelog for this version.";
    }
    print "$changes\n\n";
}