#!/bin/bash
# Copyright © 2012 Online Buddies, Inc. - All Rights Reserved

COMMAND="help"

if echo '@MODYLLIC_LIB_PATH@' | egrep -q '^[^@]'; then
	MODYLLIC_LIB_PATH="$(eval @MODYLLIC_LIB_PATH@)"
fi
next_plain_arg=

while [ -n "$*" ]; do
	next="$1" ; shift
	if [ "$next" == "--exec-path" ]; then
		next_plain_arg = "path"
	elif [ "$next" == "--version" ]; then
		echo "Modyllic Version: @VERSION@ @STATE@" 1>&2;
		exit 1;
	elif [[ "$next" =~ ^--exec-path=(.*) ]]; then
		MODYLLIC_EXEC_PATH="${BASH_REMATCH[1]}"
	elif [[ "$next" =~ ^-- ]]; then
		break;
	elif [ -n "$next_plain_arg" ]; then
		if [ "$next_plain_arg" == "path" ]; then
			MODYLLIC_EXEC_PATH="$next"
		fi
		next_plain_arg=
	else
		if [ -n "$next" ]; then
			COMMAND="$next"
		fi
		break;
	fi
done

MODYLLIC_PATH=""
if [[ "$0" =~ / ]]; then
        CMDLINE_PATH=$(dirname -- "$0")
	PATH="$CMDLINE_PATH:$PATH"
	COMMAND="$COMMAND"
	MODYLLIC_PATH="--modyllic-path=$CMDLINE_PATH"
fi

if [ -n "$MODYLLIC_EXEC_PATH" ]; then
	PATH="$MODYLLIC_EXEC_PATH:$PATH"
fi

TO_EXEC=$(which "modyllic-$COMMAND")

if [ -z "$TO_EXEC" ]; then
	myname=$(basename "$0")
	echo "$myname: '$COMMAND' is not a modyllic command. See '$myname --help'." 1>&2
	exit 1
fi

exec "$TO_EXEC" "--modyllic-path=$CMDLINE_PATH" "$@"
