#!/usr/bin/env php
<?php
/**
 * Copyright © 2011 Online Buddies, Inc. - All Rights Reserved
 *
 * @package OLB::SQL
 * @author bturner@online-buddies.com
 */

include_once dirname(realpath(__FILE__))."/../lib/OLB/SQL.php";
if ( ! class_exists('SQL',FALSE) ) {
    require_once "OLB/SQL.php";
}

$load = SQL_Commandline::args( "create", "spec", $argv );

$schema = SQL_Commandline::schema($load['spec']);
$gen = new SQL_Generator_NativeSQL();
print $gen->create_sql( $schema );
