#!/usr/bin/env php
<?php
/**
 * Copyright © 2011 Online Buddies, Inc. - All Rights Reserved
 *
 * @package OLB::SQL
 * @author bturner@online-buddies.com
 */

require_once "Modyllic/SQL.php";

$load = Modyllic_Commandline::args( "sqldiff", "oldspec newspec outputformat", $argv );

$from = Modyllic_Commandline::schema($load['oldspec']);
$to   = Modyllic_Commandline::schema($load['newspec']);
Modyllic_Commandline::warn("\r".str_repeat(" ",70)."\r");

$diff = new Modyllic_Diff( $from, $to );
if(!$load['outputformat']['format'] or $load['outputformat']['format'] == 'native') {
    $gen = new Modyllic_Generator_NativeSQL();
} else if($load['outputformat']['format'] == 'plain') {
    $gen = new Modyllic_Generator_PlainSQL();
} else {
    Modyllic_Commandline::warn("Unknown output format {$load['outputformat']['format']}\n");
    exit(1);
}
print $gen->alter_sql($diff);
