#!/usr/bin/env php
<?php
/**
 * Copyright © 2011 Online Buddies, Inc. - All Rights Reserved
 *
 * @package Modyllic
 * @author bturner@online-buddies.com
 */

require_once "Modyllic/Commandline.php";
require_once "Modyllic/Generator.php";
require_once "Modyllic/Generator/SQL.php";

$args = Modyllic_Commandline::getArgs(array(
    'description' => 'Load one or more schema and print them out',
    'options' => array(
        'dialect' => array(
            'short_name'  => '-d',
            'long_name'   => '--dialect',
            'description' => 'dialect to output in',
            'action'      => 'Dialect',
            'default'     => 'Modyllic_Generator_NativeSQL',
            ),
        'only' => array(
            'long_name'   => '--only',
            'description' => 'comma separated list of kinds of schema objects to process: database, sqlmeta, tables, views, routines, events, triggers',
            'action'      => 'StoreString',
            ) ),
    'arguments' => array(
        'spec' => array('multiple'=>true) )));

$schema = Modyllic_Commandline::schema($args->args['spec']);

$class = Modyllic_Generator::dialectToClass( $args->options['dialect'] );
$gen = new $class();

if ( isset($args->options['only']) ) {
    try {
        $only = preg_split('/\s*,\s*/',$args->options['only']);
        $gen->set_what($only);
    }
    catch (Exception $e) {
        Modyllic_Commandline::displayError($e->getMessage());
    }
}
print $gen->create_sql( $schema );
