#!/usr/bin/env php
<?php
/**
 * Copyright © 2011 Online Buddies, Inc. - All Rights Reserved
 *
 * @package Modyllic
 * @author bturner@online-buddies.com
 */

require_once "Modyllic/SQL.php";

$load = Modyllic_Commandline::args( "sqldrop", "spec", $argv );

$schema = Modyllic_Commandline::schema($load['spec']);

$gen = new Modyllic_Generator_SQL();
print $gen->drop_sql( $schema );
