#!/usr/bin/env php
<?php
/**
 * Copyright © 2011 Online Buddies, Inc. - All Rights Reserved
 *
 * @package Modyllic
 * @author bturner@online-buddies.com
 */

require_once "Modyllic/Commandline.php";
require_once "Modyllic/Generator.php";

$args = Modyllic_Commandline::getArgs(array(
    'description' => 'Preparse the SQL and generate something that can be loaded instantly.',
    'arguments' => array(
        'spec' => array('multiple'=>true) )));

$schema = Modyllic_Commandline::schema($args->args['spec']);

print serialize($schema);
