#!/usr/bin/env php
<?php
/**
 * Copyright © 2011 Online Buddies, Inc. - All Rights Reserved
 *
 * @package OLB::SQL
 * @author bturner@online-buddies.com
 */

require_once "Modyllic/SQL.php";

require_once '/opt/php/xhprof/xhprof_lib/utils/xhprof_lib.php';
require_once '/opt/php/xhprof/xhprof_lib/utils/xhprof_runs.php';
        
$load = Modyllic_Commandline::args( "create", "spec", $argv );

$ignore = array('call_user_func', 'call_user_func_array');

xhprof_enable(XHPROF_FLAGS_CPU + XHPROF_FLAGS_MEMORY, $ignore);

$schema = Modyllic_Commandline::schema($load['spec']);

$xhprof_data = xhprof_disable();
$xhprof_runs = new XHProfRuns_Default();
$run_id = $xhprof_runs->save_run($xhprof_data, "schemaload");
$profiler_url = sprintf('http://localhost/~bturner/xhprof/xhprof_html/index.php?run=%s&source=%s', $run_id, "schemaload");
echo "$profiler_url\n";
